server:
  port: 8200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka      
spring:
  application:
    name: products
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:eventsdb
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console

